stages:
  - build


.build:
  image: "migamake/haskell-build:${GHC_VER}"
  stage: build
  variables:
    LC_ALL: C.UTF-8
  before_script:
    - stack --version
    - echo ${CI_COMMIT_REF_SLUG}
  script:
    # Build it
    - stack install --system-ghc
    - stack build   --system-ghc
    - stack test    --system-ghc
    # check that CLI application is working and output is reasonable
    - stack exec -- xml-typelift-cli --version
    - stack exec -- xml-typelift-cli --help
    - stack exec -- xml-typelift-cli --schema test/data/customersOrders.xsd --types > types.hs
    - stack exec -- xml-typelift-cli --schema test/data/customersOrders.xsd > parser.hs
    - grep -z "\<data Customers.*= Customers {.*}" types.hs > /dev/null
    - grep -z "\<parseTopLevelToArray " parser.hs > /dev/null
    - stack exec -- ghc types.hs
    - stack exec -- ghc parser.hs
    # check that benchmarks is working (but limit for 10 minutes only because of slow benchmarking)
    - time 30m stack bench xml-typelift --system-ghc
  cache:
    paths:
      - .stack-work

build_8_6:
  variables:
    GHC_VER: "8.6"
  extends: .build

