stages:
  - build

.build:
  image: "migamake/haskell-build:${GHC_VER}"
  stage: build
  variables:
    LC_ALL: C.UTF-8
  before_script:
    - cabal --version
    - ghc   --version
    - echo ${CI_COMMIT_REF_SLUG}
  script:
    - ci/build.sh
  cache:
    paths:
      - ${HOME}/.cabal

stack_build:
  image: "migamake/haskell-build:8.4"
  stage: build
  variables:
    LC_ALL: C.UTF-8
  before_script:
    - stack --version
    - echo ${CI_COMMIT_REF_SLUG}
  script:
    - ci/stack-build.sh
  cache:
    paths:
      - .stack-work

build_8_6:
  variables:
    GHC_VER: "8.6"
  extends: .build

build_8_4:
  variables:
    GHC_VER: "8.4"
  extends: .build
  allow_failure: true

build_8_2:
  variables:
    GHC_VER: "8.2"
  extends: .build
  allow_failure: true

build_8_0:
  variables:
    GHC_VER: "8.0"
  extends: .build
  allow_failure: true

build_8_8:
  variables:
    GHC_VER: "8.8"
  extends: .build
  allow_failure: true

build_8_10:
  variables:
    GHC_VER: "8.10"
  extends: .build
  allow_failure: true

