stages:
  - build

buildTypelift:  # A job to build the static website - replace it with your build methods
  image: "migamake/haskell-build:8.6.2"
  stage: build
  variables:
    LC_ALL: C.UTF-8
  before_script:
    - stack --version
    - echo ${CI_COMMIT_REF_SLUG}
  script:
    - stack install
    - stack exec -- site
  cache:
    paths:
      - .stack-work

