name:                xml-typelift
version:             0.0.1
synopsis:            Converting XML Schema to Haskell datatype
description: |
    Generates datatype declarations and parser/prettyprinter
    for it from XML Schema.
    .
    Addresses handling of large documents with large schemas, like Office Open XML.
homepage:            https://github.com/DataHaskell/xml-typelift
license:             BSD3
license-file:        LICENSE
stability:           stable
author:              Michal Gajda
maintainer:          dataopt@example.com
copyright:           Copyright by Michal Gajda 2018
category:            Data, Tools, Development
build-type:          Simple
default-extensions:
  - DuplicateRecordFields
extra-source-files:
  - README.md
  - changelog.md
bug-reports:         https://github.com/DataHaskell/xml-typelift/issues
github: DataHaskell/xml-typelift

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - text
  - containers
  - data-default
  - deepseq
  - directory
  - exceptions
  - filepath
  - haskell-src-match
  - interpolatedstring-perl6
  - iso8601-duration # for testing!
  - lens
  - mtl
  - pretty-simple
  - process
  - template-haskell
  - temporary
  - uniplate
  - xeno
  - pretty-simple
  - string-conversions

flags:
  use-parser2:
    description: Add Parser2 to benchmarks
    manual: true
    default: false
  benchmark-generated-parser:
    description: Enable benchmarks for generated parser (TODO must be placed in ...)
    manual: true
    default: false
  benchmark-extended-data:
    description: Enable benchmarks on additional XML-files with wide range of sizes
    manual: true
    default: false
  benchmark-other-tools:
    description: Enable benchmarks for other tools
    manual: true
    default: false

library:
  source-dirs:
    - lib
    - lib/trustworthy
  exposed-modules:
    - FromXML
    - Errors
    # 'trustworthy' stuff:
    - Data.Vector.Safe
    - Data.Scientific.Safe
    - Xeno.DOM.Safe
  dependencies:
    - vector
    - scientific

executables:
  xml-typelift-cli:
    main: Cli.hs
    source-dirs:
      - src
      - app
    dependencies:
      - gitrev
      - optparse-applicative
      - run-haskell-module
      - xml-typelift
  mkxml:
    main: Main.hs
    source-dirs:
      - lib
      - bench/proto/mkxml
      - bench/proto/lib
    dependencies:
      - xml-typelift
      - QuickCheck
      - generic-arbitrary
      - perfect-vector-shuffle
      - scientific
      - time
      - vector
    ghc-options: -O2
  #
  # Proto-parsers runners (for debugging purpose)
  #
  parser5:
    main: Main.hs
    source-dirs:
      - lib
      - bench/proto/lib
      - bench/proto/main/parser5
      - bench/proto/parsers
      - xeno-proposal
    dependencies:
      - ghc-prim
      - megaparsec
      - pretty
      - xml-typelift
      - scientific
      - time
      - vector
    ghc-options: -O2
  parser6:
    main: Main.hs
    source-dirs:
      - lib
      - bench/proto/lib
      - bench/proto/main/parser6
      - bench/proto/parsers
      - xeno-proposal
    dependencies:
      - ghc-prim
      - megaparsec
      - pretty
      - xml-typelift
      - scientific
      - time
      - vector
    ghc-options: -O2
  parser7:
    main: Main.hs
    source-dirs:
      - lib
      - bench/proto/lib
      - bench/proto/main/parser7
      - bench/proto/parsers
      - xeno-proposal
    dependencies:
      - ghc-prim
      - megaparsec
      - pretty
      - xml-typelift
      - scientific
      - time
      - vector
    ghc-options: -O2

benchmarks:
  speed:
    source-dirs:
      - bench/speed
      - bench
      - src
    main: Main.hs
    dependencies:
      - criterion >= 1.5.0.0
      - weigh
      - xml-typelift
  memory:
    source-dirs:
      - bench/memory
      - bench
      - src
    main: Main.hs
    dependencies:
      - criterion
      - weigh
      - xml-typelift
  proto-parsers-speed:
    main: Main.hs
    source-dirs:
      - lib
      - src
      - xeno-proposal
      - bench/common
      - bench/proto
      - bench/proto/lib
      - bench/proto/parsers
      - bench/proto/speed
    dependencies:
      - criterion
      - ghc-prim
      - megaparsec
      - scientific
      - time
      - vector
      - xml-typelift
    ghc-options: -O2
    when:
      - condition: flag(use-parser2)
        cpp-options: -DBENCH_USE_PARSER2
      - condition: flag(benchmark-extended-data)
        cpp-options: -DBENCHMARK_EXTENDED_DATA_SOURCE
  proto-parsers-memory:
    main: Main.hs
    source-dirs:
      - lib
      - src
      - xeno-proposal
      - bench/common
      - bench/proto
      - bench/proto/lib
      - bench/proto/parsers
      - bench/proto/memory
    dependencies:
      - ghc-prim
      - megaparsec
      - mmap
      - scientific
      - time
      - vector
      - weigh
      - xml-typelift
    ghc-options: -O2
    when:
      - condition: flag(use-parser2)
        cpp-options: -DBENCH_USE_PARSER2
      - condition: flag(benchmark-extended-data)
        cpp-options: -DBENCHMARK_EXTENDED_DATA_SOURCE
  generated-parser-speed:
    main: Main.hs
    source-dirs:
      - bench/common
      - bench/generated
      - bench/generated/speed
    dependencies:
      - xml-typelift
      - criterion
      - scientific
      - time
      - vector
    ghc-options: -O2
    when:
      - condition: flag(benchmark-generated-parser)
        cpp-options: -DBENCHMARK_GENERATED_PARSER
      - condition: flag(benchmark-extended-data)
        cpp-options: -DBENCHMARK_EXTENDED_DATA_SOURCE
      - condition: flag(benchmark-other-tools)
        cpp-options: -DBENCHMARK_OTHER_TOOLS
        dependencies:
          - pugixml
          - hexpat
          - hexml
  generated-parser-memory:
    main: Main.hs
    source-dirs:
      - bench/common
      - bench/generated
      - bench/generated/memory
    dependencies:
      - scientific
      - time
      - vector
      - weigh
      - xml-typelift
      - mmap
    ghc-options: -O2
    when:
      - condition: flag(benchmark-generated-parser)
        cpp-options: -DBENCHMARK_GENERATED_PARSER
      - condition: flag(benchmark-extended-data)
        cpp-options: -DBENCHMARK_EXTENDED_DATA_SOURCE
      - condition: flag(benchmark-other-tools)
        cpp-options: -DBENCHMARK_OTHER_TOOLS
        dependencies:
          - pugixml
          - hexpat
          - hexml
  generated-and-proto-parsers-speed:
    main: Main.hs
    source-dirs:
      - lib
      - src
      - xeno-proposal
      - bench/common
      - bench/proto
      - bench/proto/lib
      - bench/proto/parsers
      - bench/generated
      - bench/generated-and-proto/speed
    dependencies:
      - criterion
      - ghc-prim
      - megaparsec
      - scientific
      - time
      - vector
      - xml-typelift
    ghc-options: -O2
    when:
      - condition: flag(benchmark-generated-parser)
        cpp-options: -DBENCHMARK_GENERATED_PARSER
      - condition: flag(use-parser2)
        cpp-options: -DBENCH_USE_PARSER2
      - condition: flag(benchmark-extended-data)
        cpp-options: -DBENCHMARK_EXTENDED_DATA_SOURCE
  generated-and-proto-parsers-memory:
    main: Main.hs
    source-dirs:
      - lib
      - src
      - xeno-proposal
      - bench/common
      - bench/proto
      - bench/proto/lib
      - bench/proto/parsers
      - bench/generated
      - bench/generated-and-proto/memory
    dependencies:
      - ghc-prim
      - megaparsec
      - mmap
      - scientific
      - time
      - vector
      - weigh
      - xml-typelift
    when:
      - condition: flag(benchmark-generated-parser)
        cpp-options: -DBENCHMARK_GENERATED_PARSER
      - condition: flag(use-parser2)
        cpp-options: -DBENCH_USE_PARSER2
      - condition: flag(benchmark-extended-data)
        cpp-options: -DBENCHMARK_EXTENDED_DATA_SOURCE

tests:
  unit-tests:
    source-dirs:
      - test
      - src
    main: Tests.hs
    dependencies:
      - hspec
      - xml-typelift
      - run-haskell-module
