name:                xml-typelift
version:             0.0.1
synopsis:            Converting XML Schema to Haskell datatype
description: |
    Generates datatype declarations and parser/prettyprinter
    for it from XML Schema.
    .
    Addresses handling of large documents with large schemas, like Office Open XML.
homepage:            https://github.com/DataHaskell/xml-typelift
license:             BSD3
license-file:        LICENSE
stability:           stable
author:              Michal Gajda
maintainer:          dataopt@example.com
copyright:           Copyright by Michal Gajda 2018
category:            Data, Tools
build-type:          Simple
extra-source-files:  README.md changelog.md
bug-reports:         https://github.com/DataHaskell/xml-typelift/issues
github: DataHaskell/xml-typelift
category: Development
extra-source-files:
  - changelog.md

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - containers
  - deepseq
  - filepath
  - mtl
  - xeno

library:
  source-dirs:
    - lib
  exposed-modules:
    - FromXML

executable:
  main: Main.hs
  source-dirs:
    - src
    - app
    - lib

benchmarks:
  speed:
    source-dirs:
      - bench/speed
      - src
      - lib
    main: Main.hs
    dependencies:
      - criterion >= 1.5.0.0
      - weigh
  memory:
    source-dirs:
      - bench/memory
      - src
      - lib
    main: Main.hs
    dependencies:
      - criterion
      - weigh

