version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule sync
            git submodule update --remote
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name:    Setup
          command: stack setup
      - run:
          name:    Install
          command: stack install
      - run:
          name:    Test
          command: stack test
      - run:
          name:    Make distribution archive
          command: stack bench
      - run:
          name:    Make distribution archive
          command: stack sdist
